# -*- coding: utf-8 -*-
"""Unemployment-Analysis-India.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DzNMNSdXtybbcVmXRKe9VoXsottvvkY
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')
df1 = pd.read_csv("Unemployment in India.csv")
df2 = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")
print(df1.head())
print(df2.head())

df1.info()

df1.describe()

df1.isnull().sum()

df2.info()

df2.describe()

df2.isnull().sum()

df1.columns = df1.columns.str.strip()

df2.columns = df2.columns.str.strip()
print(df1.columns)
print(df2.columns)

df1['Date'] = pd.to_datetime(df1['Date'])
df2['Date'] = pd.to_datetime(df2['Date'])

print(df1['Region'].nunique())
print(df1['Region'].unique())

trend = df1.groupby('Date')['Estimated Unemployment Rate (%)'].mean()
plt.figure(figsize=(12,6))

trend.plot()

plt.title("Unemployment Rate Over Time")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")

plt.show()

covid_data = df2.groupby('Date')['Estimated Unemployment Rate (%)'].mean()
plt.figure(figsize=(12,6))

plt.plot(covid_data.index, covid_data.values)

plt.axvline(
    pd.to_datetime('2020-03-25'),
    color='red',
    linestyle='--',
    label='Lockdown'
)

plt.legend()

plt.title("Impact of COVID-19 on Unemployment")

plt.show()

state_unemployment = (
    df1.groupby('Region')
    ['Estimated Unemployment Rate (%)']
    .mean()
    .sort_values(ascending=False)
)
print(state_unemployment.head(10))

plt.figure(figsize=(12,8))

state_unemployment.head(10).plot(kind='bar')

plt.title("Top 10 States with Highest Unemployment")

plt.ylabel("Unemployment Rate (%)")

plt.show()

pivot = df1.pivot_table(
    values='Estimated Unemployment Rate (%)',
    index='Region',
    columns='Date'
)
plt.figure(figsize=(15,10))

sns.heatmap(
    pivot,
    cmap='YlOrRd'
)

plt.title("State-wise Unemployment Heatmap")

plt.show()

df1['Area'].value_counts()
urban_rural = (
    df1.groupby('Area')
    ['Estimated Unemployment Rate (%)']
    .mean()
)
urban_rural.plot(
    kind='bar'
)

plt.title("Urban vs Rural Unemployment")

plt.show()

df1['Month'] = df1['Date'].dt.month_name()
monthly = (
    df1.groupby('Month')
    ['Estimated Unemployment Rate (%)']
    .mean()
)
monthly.plot(
    kind='bar',
    figsize=(12,6)
)

plt.title("Monthly Unemployment Trend")

plt.show()